# Copyright 2022 Espressif Systems (Shanghai) PTE LTD
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow builds test_apps for multiple IDF versions.

name: "Build test_apps"

on:
    push:
        branches:
        - master
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        idf-version: ['release-v5.2', 'release-v5.3', 'release-v5.4', 'release-v5.5']
      fail-fast: false
    container: espressif/idf:${{matrix.idf-version}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build test_apps
        shell: bash
        timeout-minutes: 100
        run: |
          . $IDF_PATH/export.sh
          pip install --upgrade idf-component-manager
          pip install idf-build-apps

          cd $GITHUB_WORKSPACE
          IDF_CCACHE_ENABLE=1 idf-build-apps build -p test_apps -t esp32s3 -vv

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test_apps-build-idf-${{matrix.idf-version}}
          path: build_esp32s3_*/
          retention-days: 7
          if-no-files-found: warn
